name: nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}

jobs:
  build-push-images:
    environment: 'Docker Push'
    runs-on: ubuntu-latest
    outputs: 
      redhat_tag: ${{ steps.redhat_tag.outputs.tag }}
    steps:
      - name: Add standard tags
        run: |
          echo 'TAGS_STANDARD<<EOF' >> $GITHUB_ENV
          echo 'type=raw,value=nightly' >> $GITHUB_ENV
          echo "type=raw,value={{date 'YYYY-MM-DD'}}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Add Red Hat standard tags
        run: |
          echo 'REDHAT_STANDARD<<EOF' >> $GITHUB_ENV
          echo 'type=raw,value=nightly,suffix=-redhat' >> $GITHUB_ENV
          echo "type=raw,value={{date 'YYYY-MM-DD'}},suffix=-redhat" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: kong/nightly-ingress-controller
          tags: ${{ env.TAGS_STANDARD }}
      - name: Docker meta (redhat)
        id: meta_redhat
        uses: docker/metadata-action@v4.0.1
        with:
          images: kong/nightly-ingress-controller
          flavor: |
            latest=false
          tags: ${{ env.REDHAT_STANDARD }}
      - name: Build binary
        id: docker_build_binary
        uses: docker/build-push-action@v3
        with:
          push: false
          file: Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: builder
          platforms: linux/amd64, linux/arm64
          build-args: |
            TAG=${{ steps.meta.outputs.version }}
            COMMIT=${{ github.sha }}
            REPO_INFO=https://github.com/${{ github.repository }}.git
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          target: distroless
          platforms: linux/amd64, linux/arm64
          build-args: |
            TAG=${{ steps.meta.outputs.version }}
            COMMIT=${{ github.sha }}
            REPO_INFO=https://github.com/${{ github.repository }}.git
      - name: Build and push Red Hat
        id: docker_build_redhat
        env:
          TAG: ${{ steps.meta.outputs.version }}
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: ${{ steps.meta_redhat.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          target: redhat
          platforms: linux/amd64, linux/arm64
          build-args: |
            TAG=${{ steps.meta.outputs.version }}
            COMMIT=${{ github.sha }}
            REPO_INFO=https://github.com/${{ github.repository }}.git
      - name: setup output 
        id: redhat_tag
        run: |
          echo "::set-output name=tag::${{ steps.meta_redhat.outputs.tags }}"


  rh-image-cert: 
    runs-on: ubuntu-latest
    needs: build-push-images
    container: 
      image: quay.io/opdev/preflight:stable
      options: --security-opt=label=disable
    steps: 
      - name: redhat preflight container check 
        run: preflight check container ${{ needs.build-push-images.outputs.redhat_tag }}